# config/mongoid.yml
development:
  clients:
    default:
      database: good_night_api_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
        max_pool_size: <%= ENV.fetch("MONGODB_MAX_POOL_SIZE") { 10 } %>